#!/bin/bash
echo "
	Running the test suite …
	========================
	
	If something goes wrong, please check in the
	LastFM settings to create or get you app ID and secret
	http://www.lastfm.fr/api/accounts
"
vendor/bin/phpunit -c phpunit.xml